name: Build and Deploy Multiple Vite Apps

on:
  push:
    branches:
      - master  # Adjust this to your main branch
  workflow_dispatch:  # Enables manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure compatibility with Vite

      # Iterate over directories and build each project
      - name: Build and Deploy Vite Apps
        run: |
          # Ensure the deploy directory exists at the root
          mkdir -p deploy
          
          # Find directories containing package.json (indicating Vite projects)
          for dir in $(find . -type f -name package.json -exec dirname {} \;); do
            dir_name=$(basename $dir)  # Extract the base directory name
            echo "Processing project in $dir"
            cd $dir

            # Check if a build script exists
            if npm run | grep -q 'build'; then
              echo "Build script found. Building project in $dir"
              # Install dependencies
              npm install
              # Build the project
              npm run build
              # Create a subdirectory in deploy for this project
              mkdir -p ../deploy/$dir_name
              mv dist/* ../deploy/$dir_name/

              # Rewrite asset paths in the built HTML files
              find ../deploy/$dir_name -name "*.html" -exec sed -i "s|/assets|/$dir_name/assets|g" {} \;

            else
              echo "Skipping $dir: No build script found"
            fi
            cd -
          done

          # Configure Git user for committing
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Navigate to deploy directory and prepare for deployment
          cd deploy
          echo "Deploy directory structure:"
          ls -R  # Debug output to verify deploy structure
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy Vite apps with adjusted paths"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages:gh-pages
