name: Build and Deploy Multiple Vite Apps

on:
  push:
    branches:
      - master  # Adjust this to your main branch
  workflow_dispatch:  # Enables manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure compatibility with Vite

      # Iterate over directories and build each project
      - name: Build and Deploy Vite Apps
        run: |
          mkdir -p deploy  # Ensure deploy directory exists
          for dir in $(find . -type f -name package.json -exec dirname {} \;); do
            dir_name=$(basename $dir)  # Get only the directory name
            echo "Processing project in $dir"
            cd $dir
            npm install
            npm run build
            mkdir -p ../deploy/$dir_name  # Use only the directory name
            mv dist/* ../deploy/$dir_name/
            cd -
          done
          cd deploy
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy Vite apps"
          git push --force git@github.com:abenrob/deck.gl-examples.git gh-pages:gh-pages
